import pandas as pd
from collections import Counter
from wordcloud import WordCloud,STOPWORDS
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
from wordcloud import ImageColorGenerator

data = pd.read_csv('/Users/gmnine/Pycharm_Projects/pythonProject/csv_file/step04_03_data_[id,review,morphs]_k.csv')
df = pd.DataFrame(data)

'''
324888,경복궁,10655 << √
553546,명동 쇼핑 거리,10352 <<
320359,창덕궁,4612
592506,인사동,6410 <<
1519813,한강 공원,1567 √
1169465,N 서울 타워,9456 << √
1046419,청계천,3946 √
1379963,북촌 한옥마을,5247 << √
1958940,홍대앞 거리,2256
6671988,동대문 디자인 플라자,2207 √
'''

# 스토어별 데이터
df_colunm = df[['store_id','morphs_selected']]
df_id = df_colunm.loc[df_colunm['store_id'] == 1169465]
print(df_id)

wordcloud_data = ''.join(list(df_id['morphs_selected']))
# print(wordcloud_data)
# print(type(wordcloud_data))

wc_data = wordcloud_data.split(', ')
# print('wc_data =',wc_data[:10])

# 리스트 요소 카운팅
counts = Counter(wc_data)
tags = counts.most_common(len(wc_data))
# print('tags =',tags)

# 이미지 마스크
m = Image.open('/Users/gmnine/Pycharm_Projects/pythonProject/png_file/mask_file/서울타워.png')
masks = np.array(m)

# ImageColorGenerator
img_color = masks
image_colors = ImageColorGenerator(img_color)

# 불용어 제거
dictionary = dict(tags)
# [1] 경복궁 불용어 제거
# del(dictionary['없'])
# del(dictionary['있다'])
# del(dictionary['오다'])
# del(dictionary['가다'])
# del(dictionary['분'])
# del(dictionary['많'])
# del(dictionary['입'])
# del(dictionary['거'])
# del(dictionary['때문'])
# del(dictionary['번'])
# del(dictionary['그렇'])
# del(dictionary['안'])
# del(dictionary['전'])
# del(dictionary['느끼다'])
# del(dictionary['기'])
# del(dictionary['등'])
# del(dictionary['ㅎ'])
# del(dictionary['중'])
# del(dictionary['날'])
# del(dictionary['시'])
# del(dictionary['복'])
# del(dictionary['정도'])
# del(dictionary['않다'])
# del(dictionary['년'])
# del(dictionary['싶다'])
# del(dictionary['크'])
# del(dictionary['요즘'])
# del(dictionary['근처'])
# del(dictionary['루'])
# del(dictionary['미'])
# del(dictionary['듯'])
# del(dictionary['때'])
# del(dictionary['대표'])
# del(dictionary['좋'])
# del(dictionary['수'])
# del(dictionary['경회'])
# del(dictionary['같'])
# del(dictionary['지다'])
# del(dictionary['만하다'])
# del(dictionary['길'])
# del(dictionary['가능하다'])
# del(dictionary['듣다'])
# del(dictionary['가보다'])
# del(dictionary['듯하다'])
# del(dictionary['넓'])
# del(dictionary['알다'])
# del(dictionary['보이다'])
# del(dictionary['살다'])
# del(dictionary['다니다'])
# del(dictionary['둘러보다'])
# del(dictionary['못하다'])
# del(dictionary['들르다'])
# del(dictionary['되다'])
# del(dictionary['찾다'])
# del(dictionary['주다'])
# del(dictionary['나다'])
# del(dictionary['모르다'])
# del(dictionary['힘들'])
# del(dictionary['속'])
# del(dictionary['비'])
# del(dictionary['나오다'])
# del(dictionary['쉬다'])
# del(dictionary['입장하다'])
# del(dictionary['들다'])
# del(dictionary['날씨'])
# del(dictionary['복판'])
# del(dictionary['하다'])
# del(dictionary['보다'])
# del(dictionary['곳'])
# del(dictionary['것'])
# [2] 서울 타워 불용어 제거
del(dictionary['번'])
del(dictionary['좋'])
del(dictionary['때'])
del(dictionary['워'])
del(dictionary['위'])
del(dictionary['줄'])
del(dictionary['있다'])
del(dictionary['그러다'])
del(dictionary['타'])
del(dictionary['힘들'])
del(dictionary['걸다'])
del(dictionary['거'])
del(dictionary['날'])
del(dictionary['ㅎ'])
del(dictionary['중'])
del(dictionary['수'])
del(dictionary['높'])
del(dictionary['분'])
del(dictionary['타우다'])
del(dictionary['만하다'])
del(dictionary['정도'])
del(dictionary['않다'])
del(dictionary['주다'])
del(dictionary['기'])
del(dictionary['없'])
del(dictionary['되다'])
del(dictionary['지다'])
del(dictionary['아쉽'])
del(dictionary['많'])
del(dictionary['위하다'])
del(dictionary['쪽'])
del(dictionary['남'])
del(dictionary['우다'])
del(dictionary['그렇'])
del(dictionary['시'])
del(dictionary['등'])
del(dictionary['전'])
del(dictionary['차'])
del(dictionary['대'])
del(dictionary['편'])
del(dictionary['크'])
del(dictionary['데'])
del(dictionary['경'])
del(dictionary['미'])
del(dictionary['나다'])
del(dictionary['듯'])
del(dictionary['오다'])
del(dictionary['같'])
del(dictionary['안'])
del(dictionary['겸'])
del(dictionary['싶다'])
del(dictionary['남산타'])
del(dictionary['때문'])
del(dictionary['보다'])
del(dictionary['가다'])
del(dictionary['것'])
del(dictionary['곳'])
del(dictionary['하다'])
# [3] 동대문 디자인 플라자 불용어 제거
# del(dictionary['있다'])
# del(dictionary['하'])
# del(dictionary['지다'])
# del(dictionary['가다'])
# del(dictionary['거'])
# del(dictionary['같'])
# del(dictionary['오다'])
# del(dictionary['라'])
# del(dictionary['길'])
# del(dictionary['나오다'])
# del(dictionary['주다'])
# del(dictionary['기'])
# del(dictionary['정도'])
# del(dictionary['자'])
# del(dictionary['전'])
# del(dictionary['없'])
# del(dictionary['들다'])
# del(dictionary['수'])
# del(dictionary['크'])
# del(dictionary['플'])
# del(dictionary['번'])
# del(dictionary['많'])
# del(dictionary['좋'])
# del(dictionary['ㅎ'])
# del(dictionary['편'])
# del(dictionary['등'])
# del(dictionary['눈'])
# del(dictionary['나다'])
# del(dictionary['듯하다'])
# del(dictionary['플라자'])
# del(dictionary['비싸'])
# del(dictionary['때문'])
# del(dictionary['넓'])
# del(dictionary['만하다'])
# del(dictionary['안'])
# del(dictionary['때'])
# del(dictionary['들르다'])
# del(dictionary['모르다'])
# del(dictionary['쉽'])
# del(dictionary['디드'])
# del(dictionary['보내다'])
# del(dictionary['않다'])
# del(dictionary['싶다'])
# del(dictionary['가지'])
# del(dictionary['팔다'])
# del(dictionary['것'])
# del(dictionary['곳'])
# del(dictionary['보다'])
# del(dictionary['하다'])
# del(dictionary['그렇'])
# del(dictionary['알다'])

wordcloud_counts = Counter(dictionary)
tagss = wordcloud_counts.most_common(len(dictionary))
print(tagss)

# Wordcloud Setting 설정
wc = WordCloud(font_path= '/Users/gmnine/Library/Fonts/MaruBuri-Bold.otf', # 위에 나왔던 경로 중 원하는 폰트로 복사
               background_color = 'white',
               width = 1000,
               height = 1000,
               max_words = 100,
               max_font_size = 300,
               # ).generate_from_frequencies(dictionary)
               mask = masks).generate_from_frequencies(dictionary)

plt.figure(figsize=(10, 8))
plt.axis('off')
# plt.imshow(wc)
plt.imshow(wc.recolor(color_func=image_colors))
plt.show()

# wc.to_file('/Users/gmnine/Pycharm_Projects/pythonProject/png_file/wc_경복궁.png')
